### ISSUE TITLE
bad argument of type `#!eof`

### ISSUE THREAD

**Issue by CGenie** [kristianlm/chicken-minissh#1]
Hello,

Trying to run the ssh chat server, however when I connect with a client I get:

```
Warning (#<thread: thread5>): in thread: (string-length) bad argument type: #!eof

        Call history:

        sshd.scm:116: minissh#userauth-accept           <--
```

The `password:` handler in `userauth-accept` works correctly, issue is with `publickey:`.

**Comment by kristianlm** [comment]
Hi CGenie, and thank for trying out this egg.

The error message you're seeing is a bug in the example code. `userauth-accept` returns `#f` on authentication failure and we shouldn't try to continue. The connection has ended but we try to read from it - hence the unexpected `#!eof`.

So your public-key authentication is not going through. You can use `ssh -d ...` to see if your client is trying to send the ed25519 public key.

I will  update the examples when I have time.

**Comment by CGenie** [comment]
Thing is I'm using Linux openssh so things should work fine. The intereseting log part is this (from `ssh -v`):

```
debug1: Local version string SSH-2.0-OpenSSH_8.0
debug1: Remote protocol version 2.0, remote software version chicken-ssh_0.1 #${df46156fb410}
debug1: no match: chicken-ssh_0.1 #${df46156fb410}
debug1: Authenticating to localhost:22022 as 'mmm'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256@libssh.org
debug1: kex: host key algorithm: ssh-ed25519
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ssh-ed25519 SHA256:JI/wpIcHUmrIoOVHgIXpQKGUIP3Ty7DUDtiiz+E2890
debug1: Host '[localhost]:22022' is known and matches the ED25519 host key.
debug1: Found key in /home/mmm/.ssh-known-hosts:87
debug1: rekey out after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey in after 134217728 blocks
```

Also, after publickey has failed, the client falls back to password and things work just fine. So I don't see exactly where that connection would have ended. I also see that the client is offering the publickeys so at least I should get to the `if signed?` code in `userauth-accept` to be able to accept or deny that key.

**Comment by kristianlm** [comment]
Can I see your `sshd.scm`?

**Comment by CGenie** [comment]
Sure:
https://chiselapp.com/user/seeg/repository/scheme-sshd/artifact/47c90b87b5537645

**Comment by kristianlm** [comment]
Are you sure that you have an ed25519 key for your ssh client? Your openssh log should say something like:

```
debug1: Offering public key: /data/data/com.termux/files/home/.ssh/id_ed25519 ED25519 SHA256:fCU4Mxy3V4wolSj8qKBim9+ahut7LHantK+NqRvTft0
```

And not just `trying`, that just means it's looking for that file on disk. Do `ssh-keygen -t 25519` to make one, it's in the readme. Let me know how that goes!

**Comment by kristianlm** [comment]
Here is a full log of my openssh client if that's useful to you. That's against the public-key server example `csi -s ~/.cache/chicken-install/minissh/examples/server-publickey.scm`.

```
OpenSSH_8.0p1, OpenSSL 1.1.1c  28 May 2019
debug1: Reading configuration data /data/data/com.termux/files/usr/etc/ssh/ssh_config
debug1: Connecting to localhost [127.0.0.1] port 22022.
debug1: Connection established.
debug1: identity file /data/data/com.termux/files/home/.ssh/id_rsa type -1
debug1: identity file /data/data/com.termux/files/home/.ssh/id_rsa-cert type -1
debug1: identity file /data/data/com.termux/files/home/.ssh/id_dsa type -1
debug1: identity file /data/data/com.termux/files/home/.ssh/id_dsa-cert type -1
debug1: identity file /data/data/com.termux/files/home/.ssh/id_ecdsa type -1
debug1: identity file /data/data/com.termux/files/home/.ssh/id_ecdsa-cert type -1
debug1: identity file /data/data/com.termux/files/home/.ssh/id_ed25519 type 3
debug1: identity file /data/data/com.termux/files/home/.ssh/id_ed25519-cert type -1
debug1: identity file /data/data/com.termux/files/home/.ssh/id_xmss type -1
debug1: identity file /data/data/com.termux/files/home/.ssh/id_xmss-cert type -1
debug1: Local version string SSH-2.0-OpenSSH_8.0
debug1: Remote protocol version 2.0, remote software version chicken-ssh_0.1 #${0e59220d1d40}
debug1: no match: chicken-ssh_0.1 #${0e59220d1d40}
debug1: Authenticating to localhost:22022 as 'u0_a190'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256@libssh.org
debug1: kex: host key algorithm: ssh-ed25519
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ssh-ed25519 SHA256:yPpL9NsQanvachAtXGfM5hCrWr2SPQgiQdOfWZ3vOi8
debug1: Host '[localhost]:22022' is known and matches the ED25519 host key.
debug1: Found key in /data/data/com.termux/files/home/.ssh/known_hosts:1
debug1: rekey out after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: SSH2_MSG_NEWKEYS received
debug1: rekey in after 134217728 blocks
debug1: Will attempt key: /data/data/com.termux/files/home/.ssh/id_rsa
debug1: Will attempt key: /data/data/com.termux/files/home/.ssh/id_dsa
debug1: Will attempt key: /data/data/com.termux/files/home/.ssh/id_ecdsa
debug1: Will attempt key: /data/data/com.termux/files/home/.ssh/id_ed25519 ED25519 SHA256:fCU4Mxy3V4wolSj8qKBim9+ahut7LHantK+NqRvTft0
debug1: Will attempt key: /data/data/com.termux/files/home/.ssh/id_xmss
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Trying private key: /data/data/com.termux/files/home/.ssh/id_rsa
debug1: Trying private key: /data/data/com.termux/files/home/.ssh/id_dsa
debug1: Trying private key: /data/data/com.termux/files/home/.ssh/id_ecdsa
debug1: Offering public key: /data/data/com.termux/files/home/.ssh/id_ed25519 ED25519 SHA256:fCU4Mxy3V4wolSj8qKBim9+ahut7LHantK+NqRvTft0
debug1: Server accepts key: /data/data/com.termux/files/home/.ssh/id_ed25519 ED25519 SHA256:fCU4Mxy3V4wolSj8qKBim9+ahut7LHantK+NqRvTft0
Welcome, 'u0_a190'
debug1: Authentication succeeded (publickey).
Authenticated to localhost ([127.0.0.1]:22022).
debug1: channel 0: new [client-session]
debug1: Entering interactive session.
debug1: pledge: network
debug1: channel 0: free: client-session, nchannels 1
Connection to localhost closed by remote host.
Transferred: sent 1952, received 580 bytes, in 0.0 seconds
Bytes per second: sent 3680845.1, received 1093693.7
debug1: Exit status -1
```

Oh, and I like your project :) Let me know if it goes anywhere!

**Comment by CGenie** [comment]
Hm, strange, I just used `ssh-keygen` described here https://github.com/kristianlm/chicken-minissh#key-api with `'ed25519` as `type`.

**Comment by CGenie** [comment]
Yup, `(ssh-keygen 'ed25519)` produces:
```
#;2> (ssh-keygen 'ed25519)
"AAAAC3NzaC1lZDI1NTE5AAAAIOepf3YuIW75TgVxG9BSPmNPCs3dtBm6f0whkDiIysAy"
#${c79e4429628f1e84707d25996d79d4c9027eb910027b347fd77c9d64a091318de7a97f762e216ef94e05711bd0523e634f0acdddb419ba7f4c21903888cac032}
```
and I still can't get this to work with the above keys.

**Comment by kristianlm** [comment]
Oh, right - that is confusing. `ssh-keygen -t ed25519` is a command from openssh, not the egg's procedure. The one in minissh is for server hostkeys and authentication whan you're using at as a client.

**Comment by CGenie** [comment]
Aaaah, OK, now I get this, I was connecting with an RSA key, doh! Closing! :)

**Comment by kristianlm** [comment]
I will see if I can clarify the readme on that one. Keep me posted if your chat app goes anywhere!

**Comment by CGenie** [comment]
It's mostly a toy project to test out various SSH ideas, chat is just a sample, I'm more interested in a distributed key-value store and such. Basically such an SSH server gives you a programming framework with proper authorization and IO taken care of so it's easy to write secure, pipe-ready shell commands. Here are some ideas:

https://chiselapp.com/user/seeg/repository/scheme-sshd/rptview?rn=1

Publickey makes things much easier to test :)

**Comment by kristianlm** [comment]
That is very cool! I've looked into ipfs and it would have been very cool to see something similar working over ssh! So your dht is very interesting, keep me posted! Best of luck to you :)

**Comment by kristianlm** [comment]
Speaking of DHT, you should look into https://ipfs.io/ if you haven't already. There's a DHT implementation there. I'd love to see a ipfs on a simpler platform like SSH with fewer go dependencies. I'm cheering you on!
